name: content → json

on:
  push:
    branches: [ main ]
    paths: [ "content/**" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[content-sync]')"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run content:sync
      - name: Commit generated JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: content sync [content-sync]"
          file_pattern: public/data/posts.json
